name: parking
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.2.0
  - bleach=3.1.5
  - boost-cpp=1.72.0
  - branca=0.4.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - colorama=0.4.3
  - contextily=1.0.0
  - cryptography=2.9.2
  - curl=7.71.1
  - cycler=0.10.0
  - dash=1.13.4
  - dash-core-components=1.10.1
  - dash-html-components=1.0.3
  - dash-renderer=1.5.1
  - dash-table=4.8.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.2.9
  - fastcache=1.1.0
  - fiona=1.8.13
  - flask=1.1.2
  - flask-compress=1.5.0
  - folium=0.11.0
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - future=0.18.2
  - gdal=3.0.4
  - geographiclib=1.50
  - geopandas=0.8.0
  - geopy=2.0.0
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.65.0
  - gmp=6.2.0
  - gmpy2=2.1.0b1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=64.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.2
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - itsdangerous=1.1.0
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9d
  - json-c=0.13.1
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.5
  - jupyter_core=4.6.3
  - jupyterlab=2.1.5
  - jupyterlab_server=1.2.0
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lcms2=2.11
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libcxx=10.0.0
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgdal=3.0.4
  - libgfortran=4.0.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - measurement=3.2.0
  - mercantile=1.1.5
  - mistune=0.8.4
  - more-itertools=8.4.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - munch=2.5.0
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.1
  - networkx=2.4
  - notebook=6.0.3
  - numpy=1.18.5
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - osmnx=0.15.1
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.1.1
  - pixman=0.38.0
  - plotly=4.8.2
  - poppler=0.87.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qgrid=1.3.1
  - rasterio=1.1.5
  - readline=8.0
  - requests=2.24.0
  - retrying=1.3.3
  - rtree=0.9.4
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - send2trash=1.5.0
  - setuptools=49.1.0
  - shapely=1.7.0
  - six=1.15.0
  - snuggs=1.4.7
  - sqlite=3.32.3
  - sympy=1.6.1
  - tabulate=0.8.7
  - tbb=2019.9
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tiledb=1.7.7
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - tzcode=2020a
  - urllib3=1.25.9
  - vincent=0.4.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xerces-c=3.2.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4

